// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "ManipA.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

ManipA::ManipA() : Subsystem("ManipA") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    topMotor = RobotMap::manipAtopMotor;
    bottomMotor = RobotMap::manipAbottomMotor;
    beltMotor = RobotMap::manipAbeltMotor;
    intakeMotor = RobotMap::manipAintakeMotor;
    compressor1 = RobotMap::manipACompressor1;
    solenoid1 = RobotMap::manipASolenoid1;
    doubleSolenoid1 = RobotMap::manipADoubleSolenoid1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void ManipA::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void ManipA::Shoot(){
	topMotor->Set(1);
	bottomMotor->Set(1);
	beltMotor->Set(.5);
}
void ManipA::StopShoot(){
	topMotor->Set(0);
	bottomMotor->Set(0);
	beltMotor->Set(0);
}
void ManipA::PickUp(){
	intakeMotor->Set(.5);
	RobotMap::manipADoubleSolenoid1->Set(DoubleSolenoid::Value::kForward);
}
void ManipA::LiftPickUp(){
	RobotMap::manipADoubleSolenoid1->Set(DoubleSolenoid::Value::kReverse);
	intakeMotor->Set(0);
}
